### ISSUE TITLE
Source Phone number provided is not yet verified

### ISSUE THREAD

**Issue by xypho** [chadsmith/OpenVBX-Android#10]
When I try to make a call I get the 
"The source phone number provided, +xxxxxxxxxxxxx is not yet verified" error screen. I've blocked out the numbers it's showing but it's a 13 digit number that isn't related to my phone in any way that I can determine. Phone is a galaxy s5 running Android 5.0

**Comment by dark7solutions** [comment]
I've realized this is the same issue as noted in a previous issue

https://github.com/chadsmith/OpenVBX-Android/issues/6

**Comment by dark7solutions** [comment]
https://github.com/chadsmith/OpenVBX-Android/issues/6
