### ISSUE TITLE
Notifications/Contacts

### ISSUE THREAD

**Issue by ChipWolf** [chadsmith/OpenVBX-Android#11]
The app delivers no notifications which renders it pretty useless.
I can't select contacts either, so I have to manually copy numbers into the app which is incredibly irritating.

Any chance of these features being added, a lot of people are using this app and it's the closest thing we have to Twilio integration on mobile without using some rubbish expensive 3rd party proprietary thing.
Honestly, I'd donate to the cause if there was a button to, I need someone to stay on top of this project for the sake of me and my team. (oh, team friendly features would be awesome too, even if it requires hosting a plugin)

**Comment by SethNJohnson** [comment]
@ChipWolf, I suggest you fork the code and hire some developers to make the changes you need and maintain them.  I'm sure you can find some off-shore freelancers on www.upwork.com that can help you relatively inexpensively.

**Comment by ChipWolf** [comment]
@SethNJohnson I would, but as @chadsmith has made such good progress at this stage it'd be a shame to go off and reinvent the wheel so to speak

**Comment by SethNJohnson** [comment]
I have reached out to @chadsmith in the past about updating and customizing this app but he did not have the time to do so.  Perhaps you will have better luck than I @ChipWolf.

**Comment by ChipWolf** [comment]
@SethNJohnson I've got a couple of colleagues re-writing a closed-source thing for now, I guess we will push some stuff downstream when the time comes. I'm confused as to why nothing like this exists yet.

**Comment by rubin110** [comment]
I would be happy to contribute/donate a small amount into the hat in order to get contacts working in some sense. The copy and paste thing and reviewing incoming messages to figure out who messaged me is painful.

**Comment by ChipWolf** [comment]
@rubin110 I'll notify you when we set up a repo, I'll invite you to the GitHub team
