### ISSUE TITLE
Hung up on "verifying OpenVBX server" on SSL

### ISSUE THREAD

**Issue by smscotten** [chadsmith/OpenVBX-Android#7]
I'm setting up OpenVBX-Android on a CoolPad Flo running Jellybean.

When I specify the URL in http I connect without any difficulty. However, if I try with https, it never gets past "verifying OpenVBX server".

My webserver seems to be configured correctly. When I browse to the server via https I get  a green lock icon (or equivalent) in every browser I use. What could be an issue is that I have a SSL cert with an intermediate certificate. It was issued by Thawte. so in my mind that shouldn't be an issue, but I wonder if OpenVBX-Android is getting hung up on the intermediate cert.

For the moment I can run it without encryption, but in the long term, ability to access via SSL (well, TLS) is a necessity. Any ideas appreciated.

**Comment by Com2000** [comment]
Are you running on iis?

**Comment by chadsmith** [comment]
This should be resolved in the 1.0 release. Let me know of that's not the case.
